import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import QueryProvider from "./QueryProvider";

const manRope = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Add the weights you need
  variable: "--font-space-grotesk", // Optional: for CSS variable usage
  display: "swap",
});

export const metadata: Metadata = {
  title: "IntervuAI",
  description: "Generated by IntervuAI - an AI interview assistant",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manRope.className}  antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
